- name: work with apache2
  hosts: all
  become: true
  tasks: 
    - name: install httpd
      yum:
        name: httpd
        state: latest
      ignore_errors: true
    - name: install apache2
      apt: 
        name: apache2
        state: latest
        
        

  