- name: work with apache2
  hosts: all
  tasks: 
    - name: install httpd
      yum:
       name: httpd
       state: latest
       Ignore errors: true
    - name: install apache2
      apt: 
       name: apache2
       state: latest

  