- name: change webpage
  hosts: all
  tasks: 
    - name: install apache2
      package:
        name: apache2
        state: latest
      tags:
        - copy
        - testing
    - name: copy webpage
      copy:
       src: ./index.html
       dest: /var/www/html/index.html
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted
        daemon_reload: true
