- name: my 1st playbook
  hosts: all
  vars:
    animal: "tiger"
  vars_files:
    - ./variable.txt
  tasks:
    - name: 1st task
      debug:
        msg: national animal f india "{{animal}}"
    - name: 2ns task
      debug:
        msg:  hello "{{animal}}"
    - name: local variable task
      debug:
        msg: "{{animal}}"
      vars:
        animal: "lion"  